apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: lessgo-secrets-provider
  namespace: lessgo
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/lessgo-492322/secrets/DATABASE_URL/versions/latest"
        path: "DATABASE_URL"
      - resourceName: "projects/lessgo-492322/secrets/REDIS_URL/versions/latest"
        path: "REDIS_URL"
      - resourceName: "projects/lessgo-492322/secrets/JWT_SECRET/versions/latest"
        path: "JWT_SECRET"
      - resourceName: "projects/lessgo-492322/secrets/JWT_ACCESS_EXPIRY/versions/latest"
        path: "JWT_ACCESS_EXPIRY"
      - resourceName: "projects/lessgo-492322/secrets/JWT_REFRESH_EXPIRY/versions/latest"
        path: "JWT_REFRESH_EXPIRY"
      - resourceName: "projects/lessgo-492322/secrets/GOOGLE_MAPS_API_KEY/versions/latest"
        path: "GOOGLE_MAPS_API_KEY"
      - resourceName: "projects/lessgo-492322/secrets/STRIPE_SECRET_KEY/versions/latest"
        path: "STRIPE_SECRET_KEY"
      - resourceName: "projects/lessgo-492322/secrets/STRIPE_WEBHOOK_SECRET/versions/latest"
        path: "STRIPE_WEBHOOK_SECRET"
      - resourceName: "projects/lessgo-492322/secrets/SMTP_HOST/versions/latest"
        path: "SMTP_HOST"
      - resourceName: "projects/lessgo-492322/secrets/SMTP_PORT/versions/latest"
        path: "SMTP_PORT"
      - resourceName: "projects/lessgo-492322/secrets/SMTP_USER/versions/latest"
        path: "SMTP_USER"
      - resourceName: "projects/lessgo-492322/secrets/SMTP_PASS/versions/latest"
        path: "SMTP_PASS"
      - resourceName: "projects/lessgo-492322/secrets/FROM_EMAIL/versions/latest"
        path: "FROM_EMAIL"
      - resourceName: "projects/lessgo-492322/secrets/AWS_ACCESS_KEY_ID/versions/latest"
        path: "AWS_ACCESS_KEY_ID"
      - resourceName: "projects/lessgo-492322/secrets/AWS_SECRET_ACCESS_KEY/versions/latest"
        path: "AWS_SECRET_ACCESS_KEY"
      - resourceName: "projects/lessgo-492322/secrets/AWS_S3_BUCKET/versions/latest"
        path: "AWS_S3_BUCKET"
      - resourceName: "projects/lessgo-492322/secrets/AWS_REGION/versions/latest"
        path: "AWS_REGION"